# Data 불러오기

In [1]:
import pandas as pd
import numpy as np

In [20]:
x_train=pd.read_csv("X_train.csv",encoding="cp949")
x_test=pd.read_csv("X_test.csv",encoding="cp949")
y_train=pd.read_csv("y_train.csv",encoding="cp949")

In [21]:
df=pd.merge(x_train,y_train)
df.head()

cust_id      총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0        0  68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1        1   2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2        2   3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3        3  16077620   4935000        NaN      기타   광주점    18  2.444444   
4        4  29050000  24000000        NaN      보석  본  점     2  1.500000   

     주말방문비율  구매주기  gender  
0  0.527027    17       0  
1  0.000000     1       0  
2  0.000000     1       1  
3  0.318182    16       1  
4  0.000000    85       0

## 결측치확인하기

In [22]:
df.isnull().sum()

cust_id       0
총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
내점일수          0
내점당구매건수       0
주말방문비율        0
구매주기          0
gender        0
dtype: int64

## 환불금액 확인 후 결측치 처리

In [24]:
df[df['환불금액'].isnull()].head()

cust_id       총구매액      최대구매액  환불금액   주구매상품 주구매지점  내점일수    내점당구매건수  \
2        2    3197000    1639000   NaN  남성 캐주얼   관악점     2   2.000000   
3        3   16077620    4935000   NaN      기타   광주점    18   2.444444   
4        4   29050000   24000000   NaN      보석  본  점     2   1.500000   
8        8  688243360  173088000   NaN      기타  본  점    18   5.944444   
9        9   26640850   13728000   NaN     농산물   대전점     1  12.000000   

     주말방문비율  구매주기  gender  
2  0.000000     1       1  
3  0.318182    16       1  
4  0.000000    85       0  
8  0.411215    15       0  
9  0.000000     0       1

In [25]:
df['환불금액']=df['환불금액'].fillna(0)
df.isnull().sum()

cust_id    0
총구매액       0
최대구매액      0
환불금액       0
주구매상품      0
주구매지점      0
내점일수       0
내점당구매건수    0
주말방문비율     0
구매주기       0
gender     0
dtype: int64

In [26]:
df.describe()

cust_id          총구매액         최대구매액          환불금액         내점일수  \
count  3500.000000  3.500000e+03  3.500000e+03  3.500000e+03  3500.000000   
mean   1749.500000  9.191925e+07  1.966424e+07  8.289786e+06    19.253714   
std    1010.507298  1.635065e+08  3.199235e+07  3.010204e+07    27.174942   
min       0.000000 -5.242152e+07 -2.992000e+06  0.000000e+00     1.000000   
25%     874.750000  4.747050e+06  2.875000e+06  0.000000e+00     2.000000   
50%    1749.500000  2.822270e+07  9.837000e+06  0.000000e+00     8.000000   
75%    2624.250000  1.065079e+08  2.296250e+07  2.642250e+06    25.000000   
max    3499.000000  2.323180e+09  7.066290e+08  5.637530e+08   285.000000   

           내점당구매건수       주말방문비율         구매주기       gender  
count  3500.000000  3500.000000  3500.000000  3500.000000  
mean      2.834963     0.307246    20.958286     0.376000  
std       1.912368     0.289752    24.748682     0.484449  
min       1.000000     0.000000     0.000000     0.000000  
25%       1.666667     0.027291     4.000000     0.000000  
50%       2.333333     0.256410    13.000000     0.000000  
75%       3.375000     0.448980    28.000000     1.000000  
max      22.083333     1.000000   166.000000     1.000000

In [27]:
df[df['총구매액']<0]

cust_id      총구매액     최대구매액         환불금액 주구매상품 주구매지점  내점일수   내점당구매건수  \
1659     1659  -2992000  -2992000    2992000.0  디자이너  본  점     1  1.000000   
3174     3174 -52421520  13616000   97222000.0    기타  본  점    18  4.444444   
3488     3488 -18905600  82306000  529602320.0  디자이너  부산본점    31  1.064516   

        주말방문비율  구매주기  gender  
1659  0.000000     0       0  
3174  0.337500    16       0  
3488  0.242424    11       0

In [29]:
x_train=df.drop(["cust_id","gender"],axis=1)
x_train

총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수    주말방문비율  \
0      68282840  11264000  6860000.0      기타   강남점    19  3.894737  0.527027   
1       2136000   2136000   300000.0     스포츠   잠실점     2  1.500000  0.000000   
2       3197000   1639000        0.0  남성 캐주얼   관악점     2  2.000000  0.000000   
3      16077620   4935000        0.0      기타   광주점    18  2.444444  0.318182   
4      29050000  24000000        0.0      보석  본  점     2  1.500000  0.000000   
...         ...       ...        ...     ...   ...   ...       ...       ...   
3495    3175200   3042900        0.0      골프  본  점     1  2.000000  1.000000   
3496   29628600   7200000  6049600.0    시티웨어  부산본점     8  1.625000  0.461538   
3497      75000     75000        0.0    주방용품   창원점     1  1.000000  0.000000   
3498    1875000   1000000        0.0     화장품  본  점     2  1.000000  0.000000   
3499  263101550  34632000  5973000.0      기타  본  점    38  2.421053  0.467391   

      구매주기  
0       17  
1        1  
2        1  
3       16  
4       85  
...    ...  
3495     0  
3496    40  
3497     0  
3498    39  
3499     8  

[3500 rows x 9 columns]

## label분리

In [60]:
y_train=df.gender
y_train

0       0
1       0
2       1
3       1
4       0
       ..
3495    1
3496    1
3497    0
3498    0
3499    0
Name: gender, Length: 3500, dtype: int64

## one hot encoding

In [61]:
x_train_dum=pd.get_dummies(x_train)
x_train_dum.head()

총구매액     최대구매액       환불금액  내점일수   내점당구매건수    주말방문비율  구매주기  주구매상품_가공식품  \
0  68282840  11264000  6860000.0    19  3.894737  0.527027    17           0   
1   2136000   2136000   300000.0     2  1.500000  0.000000     1           0   
2   3197000   1639000        0.0     2  2.000000  0.000000     1           0   
3  16077620   4935000        0.0    18  2.444444  0.318182    16           0   
4  29050000  24000000        0.0     2  1.500000  0.000000    85           0   

   주구매상품_가구  주구매상품_건강식품  ...  주구매지점_안양점  주구매지점_영등포점  주구매지점_울산점  주구매지점_인천점  \
0         0           0  ...          0           0          0          0   
1         0           0  ...          0           0          0          0   
2         0           0  ...          0           0          0          0   
3         0           0  ...          0           0          0          0   
4         0           0  ...          0           0          0          0   

   주구매지점_일산점  주구매지점_잠실점  주구매지점_전주점  주구매지점_창원점  주구매지점_청량리점  주구매지점_포항점  
0          0          0          0          0           0          0  
1          0          1          0          0           0          0  
2          0          0          0          0           0          0  
3          0          0          0          0           0          0  
4          0          0          0          0           0          0  

[5 rows x 73 columns]

In [62]:
x_test_dum=pd.get_dummies(x_test)
x_test_dum=x_test_dum.drop(['cust_id'],axis=1)
x_test_dum

총구매액     최대구매액        환불금액  내점일수    내점당구매건수    주말방문비율  구매주기  \
0      70900400  22000000   4050000.0    13   1.461538  0.789474    26   
1     310533100  38558000  48034700.0    90   2.433333  0.369863     3   
2     305264140  14825000  30521000.0   101  14.623762  0.083277     3   
3       7594080   5225000         NaN     5   2.000000  0.000000    47   
4       1795790   1411200         NaN     3   2.666667  0.125000     8   
...         ...       ...         ...   ...        ...       ...   ...   
2477   82581500  23976000         NaN     8   1.750000  0.642857    40   
2478     480000    480000         NaN     1   1.000000  0.000000     0   
2479  260003790  25750000         NaN    19   3.736842  0.915493    18   
2480   88991520  18120000         NaN     5   3.600000  0.444444    60   
2481     623700    209000         NaN     2   5.000000  0.000000    31   

      주구매상품_가공식품  주구매상품_가구  주구매상품_건강식품  ...  주구매지점_안양점  주구매지점_영등포점  주구매지점_울산점  \
0              0         0           0  ...          0           0          0   
1              0         0           0  ...          0           0          0   
2              1         0           0  ...          0           0          0   
3              0         0           0  ...          0           0          0   
4              0         0           0  ...          0           0          0   
...          ...       ...         ...  ...        ...         ...        ...   
2477           0         0           0  ...          0           0          0   
2478           0         0           0  ...          0           0          0   
2479           0         0           0  ...          0           0          0   
2480           0         0           0  ...          0           0          0   
2481           1         0           0  ...          0           1          0   

      주구매지점_인천점  주구매지점_일산점  주구매지점_잠실점  주구매지점_전주점  주구매지점_창원점  주구매지점_청량리점  \
0             0          0          0          0          0           0   
1             0          0          1          0          0           0   
2             0          0          0          0          0           0   
3             0          0          0          0          0           0   
4             0          0          0          0          0           1   
...         ...        ...        ...        ...        ...         ...   
2477          0          0          0          0          0           0   
2478          0          0          0          0          0           0   
2479          0          0          0          0          0           0   
2480          0          0          0          0          0           0   
2481          0          0          0          0          0           0   

      주구매지점_포항점  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
2477          0  
2478          0  
2479          0  
2480          0  
2481          0  

[2482 rows x 72 columns]

## Column수 조정 : train set과 test셋의 칼럼수가 다름

In [63]:
columns_set=set(x_train_dum.columns)-set(x_test_dum.columns)
columns_set

{'주구매상품_소형가전'}

### one hot encoding 누락치 조정

In [64]:
x_test_dum['주구매상품_소형가전']=0
x_test_dum['주구매상품_소형가전'].head()
    

0    0
1    0
2    0
3    0
4    0
Name: 주구매상품_소형가전, dtype: int64

In [70]:
y=y_train.copy()

## model 학습하기

### library import

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
scaler=StandardScaler()

In [68]:
x_scaled_train=scaler.fit_transform(x_train_dum)

In [69]:
x_scaled_test=scaler.fit_transform(x_test_dum)

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scaled_train,y, test_size=0.3, random_state=60, stratify=y)

In [94]:
from xgboost import XGBClassifier
model=XGBClassifier(use_label_encoder=False,max_depth=15)

In [95]:
model.fit(X_train,y_train)

[00:06:44] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=15, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=16,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [96]:
y_test_pred_proba=model.predict_proba(X_test)
y_test_pred_proba

array([[0.8396285 , 0.16037148],
       [0.89235395, 0.10764603],
       [0.98221195, 0.01778803],
       ...,
       [0.9617597 , 0.03824033],
       [0.35732126, 0.64267874],
       [0.40545344, 0.59454656]], dtype=float32)

In [97]:
y_test_proba

array([[0.61352   , 0.38647994],
       [0.81995386, 0.18004614],
       [0.86752254, 0.13247746],
       ...,
       [0.7111481 , 0.28885192],
       [0.15403527, 0.8459647 ],
       [0.24468082, 0.7553192 ]], dtype=float32)

In [98]:
from sklearn.metrics import roc_auc_score

In [99]:
score=roc_auc_score(y_test, y_test_pred_proba[:,1])

## 학습 결과 확인 하기

In [100]:
score

0.6351918059715913

### 결과 (확률 저장)

In [114]:
result_pred_proba=model.predict_proba(x_scaled_test)
result_pred_proba

array([[0.00973374, 0.99026626],
       [0.97764724, 0.02235274],
       [0.99157006, 0.00842994],
       ...,
       [0.9445411 , 0.0554589 ],
       [0.27305728, 0.7269427 ],
       [0.28077382, 0.7192262 ]], dtype=float32)

### 남자일 확률만 저장 (칼럼 인덱스 1번)

In [115]:
test_gender=pd.Series(result_pred_proba[:,1],name='gender')

In [116]:
test_gender

0       0.990266
1       0.022353
2       0.008430
3       0.783623
4       0.239267
          ...   
2477    0.973129
2478    0.175107
2479    0.055459
2480    0.726943
2481    0.719226
Name: gender, Length: 2482, dtype: float32

In [104]:
result=pd.concat([x_test.cust_id, test_gender],axis=1)
result

cust_id    gender
0        3500  0.990266
1        3501  0.022353
2        3502  0.008430
3        3503  0.783623
4        3504  0.239267
...       ...       ...
2477     5977  0.973129
2478     5978  0.175107
2479     5979  0.055459
2480     5980  0.726943
2481     5981  0.719226

[2482 rows x 2 columns]

In [105]:
result.to_csv("OOOOO.csv",index=False)